/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Organize Email': EventHandler<{ messageId: string; threadId: string; subject: string; from: string; category: { category: string; confidence: number; alternative?: unknown; promotion_score?: unknown }; urgency: { urgency: string; score: number; factors?: Record<string, number> }; importance: { importance: string; score: number; factors?: Record<string, number> }; shouldArchive?: boolean }, never>
    'Webhook API': ApiRouteHandler<{ message: { data: string; messageId: string } }, unknown, { topic: 'gmail.email.received'; data: { messageId: string; historyId: number } }>
    'Email Fetcher': EventHandler<{ messageId: string; historyId: number }, { topic: 'gmail.email.fetched'; data: never }>
    'Daily Email Summary': CronHandler<never>
    'Auto Responder Email': EventHandler<{ messageId: string; threadId: string; subject: string; from: string; category: { category: string; confidence: number; alternative?: unknown; promotion_score?: unknown }; urgency: { urgency: string; score: number }; importance: { importance: string; score: number }; shouldArchive?: boolean }, never>
    'Email Analyzer': EventHandler<never, { topic: 'gmail.email.analyzed'; data: { messageId: string; threadId: string; subject: string; from: string; category: { category: string; confidence: number; alternative?: unknown; promotion_score?: unknown }; urgency: { urgency: string; score: number; factors?: Record<string, number> }; importance: { importance: string; score: number; factors?: Record<string, number> }; shouldArchive?: boolean } }>
    'Gmail Watch': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Gmail Token Status': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Gmail Get Auth URL': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'Gmail Auth': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}